spring:
  application:
    name: departmentdb
  datasource:
    url: jdbc:postgresql://departmentdb:5432/departmentdb
    username: departmentuser
    password: departmentpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8097
  servlet:
    context-path: /api/v1
