spring:
  application:
    name: prescriptiondb
  datasource:
    url: jdbc:postgresql://prescriptiondb:5432/prescriptiondb
    username: prescriptionuser
    password: prescriptionpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8095
  servlet:
    context-path: /api/v1
