spring:
  application:
    name: patientdb
  datasource:
    url: jdbc:postgresql://patientdb:5432/patientdb
    username: patientuser
    password: patientpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8091
  servlet:
    context-path: /api/v1
