spring:
  application:
    name: premiumdb
  datasource:
    url: jdbc:postgresql://premiumdb:5432/premiumdb
    username: premiumuser
    password: premiumpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8105
  servlet:
    context-path: /api/v1
