spring:
  application:
    name: customerdb
  datasource:
    url: jdbc:postgresql://customerdb:5432/customerdb
    username: customeruser
    password: customerpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8101
  servlet:
    context-path: /api/v1
