spring:
  application:
    name: coveragedb
  datasource:
    url: jdbc:postgresql://coveragedb:5432/coveragedb
    username: coverageuser
    password: coveragepass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8107
  servlet:
    context-path: /api/v1
