spring:
  application:
    name: settlementdb
  datasource:
    url: jdbc:postgresql://settlementdb:5432/settlementdb
    username: settlementuser
    password: settlementpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8106
  servlet:
    context-path: /api/v1
